### ISSUE TITLE
How to hide Left button?

### ISSUE THREAD

**Issue by aragorniiit** [ashishtheapexian/move_item#1]
Hi Ashish

Thanks for excellent apex plugin. Is there a way to hide left button if I don't need it for my application.

Thanks
Kishore

**Comment by ashishtheapexian** [comment]
Thanks @aragorniiit ,

Which left button? Can you elaborate?

**Comment by ashishtheapexian** [comment]
Hi,
Apologies for the delay, as of the latest version I didn't do anything to hide left/right button.

Maybe in next version, I'll add this feature
